// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpRXmo54eGXVgIZb8ZdwA7ACpbH5_5Of8',
    appId: '1:226069173319:android:43058f996bd27a34ff0d62',
    messagingSenderId: '226069173319',
    projectId: 'womansapp-4d9e3',
    storageBucket: 'womansapp-4d9e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzPrrWH_cfqU4F8REoiW-2fE41O4KTIM4',
    appId: '1:226069173319:ios:05169aacee00476bff0d62',
    messagingSenderId: '226069173319',
    projectId: 'womansapp-4d9e3',
    storageBucket: 'womansapp-4d9e3.appspot.com',
    iosBundleId: 'com.example.womensApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtZkUESwC-EcwFQz3nMLgoYkX1ra_Rv8Q',
    appId: '1:226069173319:web:d067427e52fab7b7ff0d62',
    messagingSenderId: '226069173319',
    projectId: 'womansapp-4d9e3',
    authDomain: 'womansapp-4d9e3.firebaseapp.com',
    storageBucket: 'womansapp-4d9e3.appspot.com',
    measurementId: 'G-KE3F58XNVF',
  );

}